# -*- coding: utf-8 -*-
"""modelling_tuning.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hm8iRaF3j531XWUhNQsH12JB5juYtfAm
"""

from sklearn.metrics import silhouette_score

# ... (kode load data dan scaling yang tadi) ...

with mlflow.start_run(run_name="KMeans_Segmentation_With_Metrics"):
    # Training
    kmeans = KMeans(n_clusters=3, random_state=42)
    kmeans.fit(X_scaled)

    # HITUNG METRIK (Ini yang membuat Chart muncul)
    score = silhouette_score(X_scaled, kmeans.labels_)

    # Log Parameter
    mlflow.log_param("n_clusters", 3)

    # LOG METRIK KE MLFLOW
    mlflow.log_metric("silhouette_score", score)

    # Log Model
    mlflow.sklearn.log_model(kmeans, "retail_segmentation_model")

    print(f"Berhasil! Score: {score}. Cek tab 'Charts' di DagsHub sekarang.")